### ISSUE TITLE
Table Legend size

### ISSUE THREAD

**Issue by mateusconrad** [larcc-group/latex-setrem#18]
Size of tables legends must be small.
Cannot make a pull request right now.

**setrem.cls line 702**
_\captionsetup[table]{font={**small**,bf}}_

**Comment by dalvangriebler** [comment]
Are you sure? how is it written in the methodology book? 10pt?

**Comment by mateusconrad** [comment]
At least that is what my Teacher Msc. Denise Siqueira marked as an error in the document of my work. 
I will recheck by myself, this time in the book, to see wich one is the correct way.

**Comment by dalvangriebler** [comment]
Have you checked @mateusconrad ?

**Comment by dalvangriebler** [comment]
Thank you, issue solved by pull request #19
