### ISSUE TITLE
Suporte ao cabeçalho de outros cursos e também unidades da SETREM

### ISSUE THREAD

**Issue by dalvangriebler** [larcc-group/latex-setrem#20]
Configurar o template para permitir que a inclusão do cabeçalho de outros cursos da SETREM e unidades.

**Comment by claudioscheer** [comment]
Adicionei suporte aos cabeçalhos de todos os cursos superiores e técnicos.

**Comment by claudioscheer** [comment]
Adicionei no README.md informações sobre os cabeçalhos disponíveis e como trocar no LaTeX.

Apenas para deixar registrado:
- `silogo` passou a ser `sistemasinformacaologo`;
- `eclogo` passou a ser `engenhariacomputacaologo`;
- `rclogo` não existe mais;
