### ISSUE TITLE
Formatting errors

### ISSUE THREAD

**Issue by claudioscheer** [larcc-group/latex-setrem#3]
I don't know if I'm correct, but there are still some formatting errors:
- Abstract has a first paragraph indent and "RESUMO" does not;
- In references, there is an indent after the first line.

I didn't try to solve these "errors" because I don't know if it's right or not.

**Comment by LarissaGuder** [comment]
Using `\cite{} `command the output is: `Author[year]` while the correct is `Author(year)`.
The same applies to the other citation commands.

**Comment by dalvangriebler** [comment]
Issue solved by @GabrielFim
