### ISSUE TITLE
Advisors

### ISSUE THREAD

**Issue by mateusconrad** [larcc-group/latex-setrem#6]
By now, the template only allows the insertion of only one /advisor and /co-advisor. 
The suggestion is to apply the same logic as the /author field, implementing a counter to get advisora, advisorb, etc.

**Comment by dalvangriebler** [comment]
Thank you @mateusconrad, if you have the solution, you can make a pull request and I will just verify if you code is ok.

**Comment by GabrielFim** [comment]
#11 This is a way around, it works but is not the most right one.

**Comment by dalvangriebler** [comment]
There is something wrong in your code @GabrielFim in #12. Please check again, maybe you forgot yo commit something else.

**Comment by dalvangriebler** [comment]
It is still not working @GabrielFim  when I add more than one advisor, please check the original repository now. There may be missing something.

**Comment by dalvangriebler** [comment]
Issue solved with #16, thanks to @GabrielFim
